version: '3.4'

services:
  stealthmarsrover.web:
    image: ${DOCKER_REGISTRY-}stealthmarsroverweb
    build:
      context: .
      dockerfile: StealthMarsRover.Web\Dockerfile

  stealthmarsrover.angular.app:
    image: ${DOCKER_REGISTRY-}stealthmarsroverangularapp
    build:
      context: .
      dockerfile: StealthMarsRover.Web/ClientApp/Dockerfile
    ports:
      - "4200:4200" 
      - "49153:49153"
    volumes:
      - ./StealthMarsRover.Web/ClientApp:/app